# Acme/DemoBundle/Resources/config/admin.yml
services:
    sonata.admin.post:
        class: Perso\SiteBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Articles" }
        arguments:
            - ~
            - Perso\SiteBundle\Entity\Site\Post
            - ~
        calls:
            - [ setTranslationDomain, [PersoSiteBundle]]           
    sonata.admin.experience:
        class: Perso\SiteBundle\Admin\ExperienceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Experiences" }
        arguments:
            - ~
            - Perso\SiteBundle\Entity\Site\Experience
            - ~
        calls:
            - [ setTranslationDomain, [PersoSiteBundle]]
    sonata.admin.formation:
        class: Perso\SiteBundle\Admin\FormationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Formations" }
        arguments:
            - ~
            - Perso\SiteBundle\Entity\Site\Formation
            - ~
        calls:
            - [ setTranslationDomain, [PersoSiteBundle]]
    sonata.admin.category:
        class: Perso\SiteBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Categories" }
        arguments:
            - ~
            - Perso\SiteBundle\Entity\Site\Category
            - ~
        calls:
            - [ setTranslationDomain, [PersoSiteBundle]]