parameters:
#    perso_site.example.class: Perso\SiteBundle\Example

services:
#    perso_site.example:
#        class: %perso_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
