<?php

namespace Perso\SiteBundle\Entity\Site;

use Doctrine\ORM\EntityRepository;
use Perso\SiteBundle\PersoSiteBundle;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{


}
